# Generated by Django 3.1.4 on 2020-12-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IpUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.DateTimeField(max_length=10)),
                ('ip_addr', models.CharField(max_length=10)),
                ('mac_addr', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'ipuser',
                'ordering': ['user'],
            },
        ),
    ]
