# Generated by Django 3.1.4 on 2020-12-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipuser',
            name='user',
            field=models.CharField(max_length=10),
        ),
    ]
