# Generated by Django 3.1.4 on 2020-12-22 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipuser', '0002_auto_20201222_2255'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ipuser',
            table='ipusers',
        ),
    ]
