# Generated by Django 3.1.4 on 2020-12-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipuser', '0003_auto_20201222_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipuser',
            name='ip_addr',
            field=models.CharField(max_length=17),
        ),
        migrations.AlterField(
            model_name='ipuser',
            name='mac_addr',
            field=models.CharField(max_length=17),
        ),
    ]
